# Generated by Django 4.1.2 on 2022-10-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='highestbid',
            field=models.PositiveSmallIntegerField(blank=True, default=models.PositiveSmallIntegerField(default=0)),
        ),
    ]
