# Generated by Django 4.1.2 on 2022-10-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listings_highestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='highestbid',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
