# Generated by Django 4.1.2 on 2022-10-19 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AddField(
            model_name='listings',
            name='caption',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='No Image', upload_to='images'),
        ),
    ]
