# Generated by Django 4.1.2 on 2022-10-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_delete_uploadimage_listings_caption_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='content',
            field=models.TextField(),
        ),
    ]
