# Generated by Django 4.1.2 on 2022-10-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='caption',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='content',
            new_name='description',
        ),
    ]
