# Generated by Django 4.1.2 on 2022-10-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_caption_listings_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('UNK', 'Unknown'), ('AC', 'Accessories'), ('TPS', 'Tops'), ('JKT', 'Jackets'), ('SWT', 'Sweaters'), ('SRT', 'Shirts'), ('ST', 'Suits'), ('DRS', 'Dresses'), ('PN', 'Pants'), ('JN', 'Jeans'), ('SHR', 'Shorts'), ('SWM', 'Swim'), ('SHO', 'Shoes')], max_length=3),
        ),
    ]
