# Generated by Django 4.1.2 on 2022-10-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('TPS', 'Tops'), ('FOD', 'Food'), ('ART', 'Art'), ('CLT', 'Clothing'), ('UNK', 'Unknown'), ('AC', 'Accessories')], max_length=3),
        ),
    ]
