# Generated by Django 4.1.2 on 2022-10-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listings_image_listings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='No Image', upload_to='images'),
        ),
    ]
