# Generated by Django 4.1.2 on 2022-10-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listings_category_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
