# Generated by Django 4.1.2 on 2022-10-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='user',
        ),
    ]
