# Generated by Django 4.1.2 on 2022-10-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highestbid',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
