# Generated by Django 4.1.2 on 2022-10-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('TCH', 'Electronics'), ('FOD', 'Food'), ('ART', 'Art'), ('CLT', 'Clothing'), ('AC', 'Accessories'), ('UNK', 'Unknown')], max_length=3),
        ),
    ]
